INSERT INTO location (name) VALUES ('Louvre Museum');
INSERT INTO location (name) VALUES ('Rosslyn Chapel');
INSERT INTO location (name) VALUES ('Temple Church');
INSERT INTO location (name) VALUES ('Château Villette');
INSERT INTO location (name) VALUES ('Lincoln Cathedral');
INSERT INTO location (name) VALUES ('Westminster Abbey');
INSERT INTO location (name) VALUES ('Saint-Sulpice');
INSERT INTO location (name) VALUES ('Salisbury Cathedral');
INSERT INTO location (name) VALUES ('King\`s College');
INSERT INTO location (name) VALUES ('Fleet Street');